#!/usr/bin/env node
/**
 * =============================================================================
 * Setup Frontend Environment File
 * =============================================================================
 * Bu script .env.local faylini yaratadi.
 * 
 * Usage:
 *     node setup_env.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function createEnvFile() {
  const envPath = path.join(__dirname, '.env.local');
  
  if (fs.existsSync(envPath)) {
    const response = await question('.env.local file already exists. Overwrite? (y/N): ');
    if (response.toLowerCase() !== 'y') {
      console.log('Aborted.');
      rl.close();
      return;
    }
  }
  
  const apiUrl = await question('Backend API URL (default: http://localhost:8000): ') || 'http://localhost:8000';
  
  const envContent = `# =============================================================================
# CareerUZ - Frontend Environment Configuration
# =============================================================================
# AUTO-GENERATED by setup_env.js

# -----------------------------------------------------------------------------
# API Configuration
# -----------------------------------------------------------------------------
NEXT_PUBLIC_API_URL=${apiUrl}

# -----------------------------------------------------------------------------
# App Configuration
# -----------------------------------------------------------------------------
NEXT_PUBLIC_APP_NAME="CareerUZ"
NEXT_PUBLIC_APP_VERSION="1.0.0"

# -----------------------------------------------------------------------------
# Feature Flags
# -----------------------------------------------------------------------------
NEXT_PUBLIC_ENABLE_AI_FEATURES=true
NEXT_PUBLIC_ENABLE_PAYMENTS=false
NEXT_PUBLIC_ENABLE_ANALYTICS=false

# -----------------------------------------------------------------------------
# Default Language
# -----------------------------------------------------------------------------
NEXT_PUBLIC_DEFAULT_LOCALE=uz

# -----------------------------------------------------------------------------
# Analytics (optional)
# -----------------------------------------------------------------------------
NEXT_PUBLIC_GA_TRACKING_ID=
NEXT_PUBLIC_SENTRY_DSN=
`;
  
  fs.writeFileSync(envPath, envContent, 'utf-8');
  
  console.log(`\n✅ .env.local file created at: ${envPath}`);
  console.log('\n📝 Next steps:');
  console.log('   1. Make sure backend is running at ' + apiUrl);
  console.log('   2. Enable payment features when ready');
  console.log('   3. Add analytics keys if needed');
  console.log('\n🚀 Run: npm run dev');
  
  rl.close();
}

createEnvFile().catch(err => {
  console.error('Error:', err);
  rl.close();
  process.exit(1);
});









