#!/usr/bin/env python3
"""
=============================================================================
Setup Environment File
=============================================================================
Bu script .env faylini yaratadi.

Usage:
    python setup_env.py
"""

import os
import secrets
from pathlib import Path

def generate_secret_key(length=64):
    """Generate a secure random secret key."""
    return secrets.token_urlsafe(length)

def create_env_file():
    """Create .env file with default values."""
    
    env_path = Path(__file__).parent / ".env"
    
    if env_path.exists():
        response = input(".env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Aborted.")
            return
    
    # Generate secure keys
    secret_key = generate_secret_key()
    jwt_secret_key = generate_secret_key()
    
    env_content = f"""# =============================================================================
# SmartCareer AI - Backend Environment Configuration
# =============================================================================
# AUTO-GENERATED by setup_env.py

# -----------------------------------------------------------------------------
# APPLICATION
# -----------------------------------------------------------------------------
APP_NAME="SmartCareer AI"
APP_VERSION="1.0.0"
DEBUG=true
SECRET_KEY={secret_key}
ENVIRONMENT=development

# -----------------------------------------------------------------------------
# DATABASE
# -----------------------------------------------------------------------------
# Development: SQLite
DATABASE_URL=sqlite:///./smartcareer.db

# Production: PostgreSQL (uncomment below)
# DATABASE_URL=postgresql://smartcareer:password@localhost:5432/smartcareer

# -----------------------------------------------------------------------------
# JWT AUTHENTICATION
# -----------------------------------------------------------------------------
JWT_SECRET_KEY={jwt_secret_key}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7

# -----------------------------------------------------------------------------
# GOOGLE GEMINI AI (FREE!)
# -----------------------------------------------------------------------------
# Get your key: https://ai.google.dev/
GEMINI_API_KEY=
GEMINI_MODEL=gemini-2.5-flash
AI_PROVIDER=gemini

# -----------------------------------------------------------------------------
# OPENAI (Optional - Paid)
# -----------------------------------------------------------------------------
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4-turbo-preview

# -----------------------------------------------------------------------------
# EMAIL (SMTP)
# -----------------------------------------------------------------------------
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=noreply@smartcareer.uz
SMTP_FROM_NAME=SmartCareer AI
SMTP_USE_TLS=true

# SendGrid (Production)
SENDGRID_API_KEY=

# Frontend URL
FRONTEND_URL=http://localhost:3000

# Support email
SUPPORT_EMAIL=support@smartcareer.uz

# -----------------------------------------------------------------------------
# CORS
# -----------------------------------------------------------------------------
CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000

# -----------------------------------------------------------------------------
# RATE LIMITING
# -----------------------------------------------------------------------------
RATE_LIMIT_ENABLED=true
RATE_LIMIT_PER_MINUTE=60
LOGIN_RATE_LIMIT_PER_MINUTE=5
"""
    
    # Write to file
    with open(env_path, 'w', encoding='utf-8') as f:
        f.write(env_content)
    
    print(f"✅ .env file created at: {env_path}")
    print("\n🔑 Secure keys have been generated automatically.")
    print("\n📝 Next steps:")
    print("   1. Add your GEMINI_API_KEY (get it from https://ai.google.dev/)")
    print("   2. Configure SMTP settings for email (optional)")
    print("   3. Update DATABASE_URL for production if needed")
    print("\n🚀 Run: uvicorn app.main:app --reload")

if __name__ == "__main__":
    create_env_file()









