export type SkillProfile = {
  label: string;
  keywords: string[];
  technical: string[];
  soft: string[];
};

type ResumeLocale = "uz" | "ru";

export const commonSkills: Readonly<{
  technical: string[];
  soft: string[];
}> = {
  technical: [
    "MS Excel",
    "Google Sheets",
    "Microsoft Office",
    "Email communication",
    "Report writing",
    "Data entry",
    "Document management",
    "Presentation skills",
    "CRM basics",
    "Task prioritization",
    "Internet research",
    "Time management tools",
  ],
  soft: [
    "Communication",
    "Teamwork",
    "Problem solving",
    "Time management",
    "Adaptability",
    "Attention to detail",
    "Critical thinking",
    "Responsibility",
    "Organization",
    "Customer focus",
  ],
};

const SKILL_LABELS: Record<ResumeLocale, Record<string, string>> = {
  uz: {
    "Financial reporting": "Moliyaviy hisobot",
    "General ledger": "Bosh kitob hisobi",
    "Tax accounting": "Soliq hisobi",
    Payroll: "Ish haqi hisobi",
    "Accounts payable": "Kreditorlik hisoblari",
    "Accounts receivable": "Debitorlik hisoblari",
    Reconciliation: "Solishtirma tahlil",
    "Cost accounting": "Xarajatlar hisobi",
    Accuracy: "Aniqlik",
    Integrity: "Halollik",
    Confidentiality: "Maxfiylik",
    "Business acumen": "Biznesni tushunish",
    "Decision making": "Qaror qabul qilish",
    "Financial modeling": "Moliyaviy modellashtirish",
    Budgeting: "Byudjetlashtirish",
    Forecasting: "Prognozlash",
    "Variance analysis": "Farqlar tahlili",
    Valuation: "Baholash",
    "Scenario analysis": "Ssenariy tahlili",
    "Audit planning": "Audit rejalashtirish",
    "Risk assessment": "Risklarni baholash",
    Compliance: "Muvofiqlik nazorati",
    Documentation: "Hujjatlashtirish",
    IFRS: "MHXS (IFRS)",
    "Email communication": "Email orqali muloqot",
    "Report writing": "Hisobot yozish",
    "Data entry": "Ma'lumot kiritish",
    "Document management": "Hujjatlarni boshqarish",
    "Presentation skills": "Taqdimot ko'nikmalari",
    "Task prioritization": "Vazifalarni ustuvorlashtirish",
    "Internet research": "Internet tadqiqoti",
    "Time management tools": "Vaqt boshqaruvi vositalari",
    Communication: "Muloqot",
    Teamwork: "Jamoada ishlash",
    "Problem solving": "Muammo yechish",
    "Time management": "Vaqtni boshqarish",
    Adaptability: "Moslashuvchanlik",
    "Attention to detail": "Detallarga e'tibor",
    "Critical thinking": "Tanqidiy fikrlash",
    Responsibility: "Mas'uliyat",
    Organization: "Tashkiliylik",
    "Customer focus": "Mijozga yo'nalish",
    "Analytical thinking": "Tahliliy fikrlash",
    Collaboration: "Hamkorlik",
    Ownership: "Javobgarlikni olish",
    Leadership: "Liderlik",
    Creativity: "Ijodkorlik",
    Empathy: "Empatiya",
    Patience: "Sabr",
    Negotiation: "Muzokara",
    "Service mindset": "Xizmatga yo'naltirilganlik",
    "Result orientation": "Natijaga yo'nalganlik",
    "Relationship building": "Aloqa o'rnatish",
    Resilience: "Barqarorlik",
    "Strategic thinking": "Strategik fikrlash",
    Networking: "Tarmoq qurish",
    Initiative: "Tashabbuskorlik",
    "Project coordination": "Loyihalarni muvofiqlashtirish",
    "Data-driven mindset": "Ma'lumotga asoslangan fikrlash",
    "Audience empathy": "Auditoriyani tushunish",
    "Conflict resolution": "Nizolarni hal qilish",
    Accountability: "Javobgarlik",
    Ethics: "Etika",
    Objectivity: "Xolislik",
    Persuasion: "Ishontirish",
    Curiosity: "Qiziquvchanlik",
    "User empathy": "Foydalanuvchini tushunish",
    "Incident management": "Insident boshqaruvi",
    "Stress resilience": "Stressga bardoshlilik",
    Persistence: "Qat'iyatlilik",
    "Business understanding": "Biznesni tushunish",
    "Research mindset": "Tadqiqotga yo'naltirilgan fikrlash",
    "Internal controls": "Ichki nazorat",
    "Financial statements": "Moliyaviy hisobot shakllari",
    "Sampling techniques": "Tanlama usullari",
    "Audit reporting": "Audit hisobotlari",
    "Excel advanced": "Kengaytirilgan Excel",
    "KPI tracking": "KPI kuzatuvi",
    Presentation: "Taqdimot",
    Wireframing: "Wireframe yaratish",
    Prototyping: "Prototip yaratish",
    "User research": "Foydalanuvchi tadqiqoti",
    "Design systems": "Dizayn tizimlari",
    "Usability testing": "Qulaylik testlari",
    "Information architecture": "Axborot arxitekturasi",
    "Interaction design": "Interaktiv dizayn",
    "Visual hierarchy": "Vizual ierarxiya",
    "Brand identity": "Brend identikasi",
    "Layout design": "Maket dizayni",
    "Color theory": "Ranglar nazariyasi",
    "Asset preparation": "Materiallarni tayyorlash",
    "Lead qualification": "Lidlarni saralash",
    "Pipeline management": "Savdo pipeline boshqaruvi",
    "Sales forecasting": "Savdo prognozi",
    "Client presentations": "Mijozlar uchun taqdimot",
    "Objection handling": "E'tirozlar bilan ishlash",
    "Proposal writing": "Taklif hujjatini yozish",
    Prospecting: "Yangi mijozlarni izlash",
    Upselling: "Qo'shimcha sotuv",
    "Market mapping": "Bozor xaritalash",
    "Partnership strategy": "Hamkorlik strategiyasi",
    "Deal structuring": "Bitim tuzilmasini yaratish",
    "Competitive analysis": "Raqobatchilar tahlili",
    "Proposal development": "Taklifni ishlab chiqish",
    "Revenue planning": "Daromad rejalashtirish",
    "Stakeholder management": "Manfaatdor tomonlar bilan ishlash",
    "Candidate sourcing": "Nomzodlarni topish",
    Interviewing: "Intervyu o'tkazish",
    Onboarding: "Onboarding jarayoni",
    "Employer branding": "Ish beruvchi brendi",
    "HR documentation": "HR hujjatlari",
    "Performance review process": "Samaradorlik baholash jarayoni",
    "Compensation benchmarking": "Kompensatsiya bozor tahlili",
    "Cross functional coordination": "Bo'limlararo muvofiqlashtirish",
    "Workflow mapping": "Ish jarayonlarini xaritalash",
    "Ticketing systems": "Murojaat (ticket) tizimlari",
    "Live chat support": "Jonli chat qo'llab-quvvatlashi",
    "Email support": "Email orqali qo'llab-quvvatlash",
    "Knowledge base management": "Bilim bazasini boshqarish",
    "Escalation handling": "Eskalatsiya boshqaruvi",
    "Call handling": "Qo'ng'iroqlarni yuritish",
    "Product documentation": "Mahsulot hujjatlari",
    "Lesson planning": "Dars rejalashtirish",
    "Curriculum development": "O'quv dasturini ishlab chiqish",
    "Classroom management": "Sinfni boshqarish",
    "Assessment design": "Baholash tizimini loyihalash",
    "Online teaching tools": "Onlayn ta'lim vositalari",
    "Student progress tracking": "Talaba rivojlanishini kuzatish",
    "Educational technology": "Ta'lim texnologiyalari",
    "Learning strategies": "O'qitish strategiyalari",
    "Academic reporting": "Akademik hisobotlar",
    "Written translation": "Yozma tarjima",
    "Simultaneous interpretation": "Sinxron tarjima",
    "Terminology management": "Terminologiya boshqaruvi",
    "Localization QA": "Lokalizatsiya sifat nazorati",
    "Style guide compliance": "Uslub yo'riqnomasiga moslik",
    Subtitling: "Subtitr tayyorlash",
    "Language quality review": "Til sifati auditi",
    "Legal research": "Yuridik tadqiqot",
    "Contract drafting": "Shartnoma tuzish",
    "Case analysis": "Ish holatini tahlil qilish",
    "Regulatory review": "Normativ hujjatlarni ko'rib chiqish",
    "Legal writing": "Yuridik yozuv",
    "Corporate law basics": "Korporativ huquq asoslari",
    "Client consultation": "Mijoz konsultatsiyasi",
    "Vendor sourcing": "Ta'minotchini topish",
    "RFQ management": "RFQ boshqaruvi",
    "Contract negotiation": "Shartnoma muzokarasi",
    "Cost analysis": "Xarajat tahlili",
    "Purchase order management": "Buyurtmalar boshqaruvi",
    "Supplier evaluation": "Ta'minotchini baholash",
    "Inventory coordination": "Zaxiralarni muvofiqlashtirish",
    "Spend reporting": "Xarajatlar hisoboti",
    "Warehouse operations": "Ombor operatsiyalari",
    "Customs documentation": "Bojxona hujjatlari",
    "TMS systems": "TMS tizimlari",
    "Supplier coordination": "Ta'minotchilar bilan muvofiqlashtirish",
    "Delivery scheduling": "Yetkazib berish rejalashtirish",
    "Travel coordination": "Safarlarni muvofiqlashtirish",
    "MS Office": "MS Office",
    "Record keeping": "Hisob-kitob yuritish",
    Correspondence: "Yozishmalar",
    "Patient assessment": "Bemor holatini baholash",
    Diagnosis: "Tashxis",
    "Clinical documentation": "Klinik hujjatlashtirish",
    "Medical ethics": "Tibbiy etika",
    "Electronic health records": "Elektron tibbiy kartalar",
    "Emergency response": "Shoshilinch javob",
    "Preventive care": "Profilaktik parvarish",
    "Patient education": "Bemorni xabardor qilish",
    "Interdisciplinary coordination": "Ko'p tarmoqli hamkorlik",
    "Patient care": "Bemor parvarishi",
    "Vital signs monitoring": "Hayotiy ko'rsatkichlarni kuzatish",
    "Medication administration": "Dori qo'llash",
    "Infection control": "Infeksiya nazorati",
    "Emergency support": "Favqulodda yordam",
    "Care planning": "Parvarish rejalashtirish",
    "Requirements gathering": "Talablarni yig'ish",
    "Stakeholder interviews": "Manfaatdor tomonlar intervyusi",
    "Gap analysis": "Bo'shliq tahlili",
    "Acceptance criteria": "Qabul mezonlari",
    "Backlog refinement": "Backlogni aniqlashtirish",
    "SEO writing": "SEO matn yozish",
    Research: "Tadqiqot",
    CMS: "CMS",
    "Tone of voice": "Brend uslubi",
    "Social media copy": "Ijtimoiy tarmoq matni",
    "Email copy": "Email matni",
    "Vulnerability assessment": "Zaifliklarni baholash",
    "Threat analysis": "Tahdidlar tahlili",
    "Security policies": "Xavfsizlik siyosatlari",
    "Penetration testing basics": "Pen-test asoslari",
    "Endpoint security": "Endpoint xavfsizligi",
    "Windows Server": "Windows Server",
    "Linux administration": "Linux administratsiyasi",
    "Network configuration": "Tarmoq sozlash",
    "Active Directory": "Active Directory",
    "Backup and recovery": "Zaxiralash va tiklash",
    "User access management": "Foydalanuvchi kirishini boshqarish",
    "Hardware troubleshooting": "Qurilma nosozliklarini bartaraf etish",
    Virtualization: "Virtualizatsiya",
    "Monitoring tools": "Monitoring vositalari",
    "Security patching": "Xavfsizlik patchlarini qo'llash",
  },
  ru: {
    "Financial reporting": "Финансовая отчетность",
    "General ledger": "Главная книга",
    "Tax accounting": "Налоговый учет",
    Payroll: "Расчет заработной платы",
    "Accounts payable": "Кредиторская задолженность",
    "Accounts receivable": "Дебиторская задолженность",
    Reconciliation: "Сверка счетов",
    "Cost accounting": "Учет затрат",
    Accuracy: "Точность",
    Integrity: "Честность",
    Confidentiality: "Конфиденциальность",
    "Business acumen": "Бизнес-понимание",
    "Decision making": "Принятие решений",
    "Financial modeling": "Финансовое моделирование",
    Budgeting: "Бюджетирование",
    Forecasting: "Прогнозирование",
    "Variance analysis": "Факторный анализ отклонений",
    Valuation: "Оценка",
    "Scenario analysis": "Сценарный анализ",
    "Audit planning": "Планирование аудита",
    "Risk assessment": "Оценка рисков",
    Compliance: "Комплаенс",
    Documentation: "Документирование",
    IFRS: "МСФО (IFRS)",
    "Email communication": "Деловая переписка",
    "Report writing": "Подготовка отчетов",
    "Data entry": "Ввод данных",
    "Document management": "Документооборот",
    "Presentation skills": "Навыки презентации",
    "Task prioritization": "Приоритизация задач",
    "Internet research": "Интернет-исследование",
    "Time management tools": "Инструменты тайм-менеджмента",
    Communication: "Коммуникация",
    Teamwork: "Работа в команде",
    "Problem solving": "Решение проблем",
    "Time management": "Управление временем",
    Adaptability: "Адаптивность",
    "Attention to detail": "Внимание к деталям",
    "Critical thinking": "Критическое мышление",
    Responsibility: "Ответственность",
    Organization: "Организованность",
    "Customer focus": "Ориентация на клиента",
    "Analytical thinking": "Аналитическое мышление",
    Collaboration: "Сотрудничество",
    Ownership: "Ответственность за результат",
    Leadership: "Лидерство",
    Creativity: "Креативность",
    Empathy: "Эмпатия",
    Patience: "Терпение",
    Negotiation: "Переговоры",
    "Service mindset": "Ориентация на сервис",
    "Result orientation": "Ориентация на результат",
    "Relationship building": "Построение отношений",
    Resilience: "Устойчивость",
    "Strategic thinking": "Стратегическое мышление",
    Networking: "Нетворкинг",
    Initiative: "Инициативность",
    "Project coordination": "Координация проектов",
    "Data-driven mindset": "Подход на основе данных",
    "Audience empathy": "Понимание аудитории",
    "Conflict resolution": "Разрешение конфликтов",
    Accountability: "Подотчетность",
    Ethics: "Этика",
    Objectivity: "Объективность",
    Persuasion: "Убеждение",
    Curiosity: "Любознательность",
    "User empathy": "Понимание пользователя",
    "Incident management": "Управление инцидентами",
    "Stress resilience": "Стрессоустойчивость",
    Persistence: "Настойчивость",
    "Business understanding": "Понимание бизнеса",
    "Research mindset": "Исследовательский подход",
    "Internal controls": "Внутренний контроль",
    "Financial statements": "Финансовая отчетность",
    "Sampling techniques": "Методы выборки",
    "Audit reporting": "Аудиторская отчетность",
    "Excel advanced": "Продвинутый Excel",
    "KPI tracking": "Мониторинг KPI",
    Presentation: "Презентация",
    Wireframing: "Проработка wireframe",
    Prototyping: "Прототипирование",
    "User research": "Исследование пользователей",
    "Design systems": "Дизайн-системы",
    "Usability testing": "Тестирование удобства",
    "Information architecture": "Информационная архитектура",
    "Interaction design": "Дизайн взаимодействия",
    "Visual hierarchy": "Визуальная иерархия",
    "Brand identity": "Айдентика бренда",
    "Layout design": "Дизайн макета",
    "Color theory": "Теория цвета",
    "Asset preparation": "Подготовка материалов",
    "Lead qualification": "Квалификация лидов",
    "Pipeline management": "Управление воронкой продаж",
    "Sales forecasting": "Прогноз продаж",
    "Client presentations": "Презентации для клиентов",
    "Objection handling": "Работа с возражениями",
    "Proposal writing": "Подготовка коммерческих предложений",
    Prospecting: "Поиск новых клиентов",
    Upselling: "Дополнительные продажи",
    "Market mapping": "Картирование рынка",
    "Partnership strategy": "Партнерская стратегия",
    "Deal structuring": "Структурирование сделок",
    "Competitive analysis": "Конкурентный анализ",
    "Proposal development": "Разработка предложений",
    "Revenue planning": "Планирование выручки",
    "Stakeholder management": "Управление стейкхолдерами",
    "Candidate sourcing": "Поиск кандидатов",
    Interviewing: "Проведение интервью",
    Onboarding: "Онбординг",
    "Employer branding": "Бренд работодателя",
    "HR documentation": "HR-документация",
    "Performance review process": "Процесс оценки эффективности",
    "Compensation benchmarking": "Бенчмаркинг компенсаций",
    "Cross functional coordination": "Кросс-функциональная координация",
    "Workflow mapping": "Картирование процессов",
    "Ticketing systems": "Тикет-системы",
    "Live chat support": "Поддержка в live-чате",
    "Email support": "Email-поддержка",
    "Knowledge base management": "Управление базой знаний",
    "Escalation handling": "Управление эскалациями",
    "Call handling": "Обработка звонков",
    "Product documentation": "Документация продукта",
    "Lesson planning": "Планирование уроков",
    "Curriculum development": "Разработка учебной программы",
    "Classroom management": "Управление классом",
    "Assessment design": "Проектирование оценивания",
    "Online teaching tools": "Инструменты онлайн-обучения",
    "Student progress tracking": "Отслеживание прогресса студентов",
    "Educational technology": "Образовательные технологии",
    "Learning strategies": "Стратегии обучения",
    "Academic reporting": "Академическая отчетность",
    "Written translation": "Письменный перевод",
    "Simultaneous interpretation": "Синхронный перевод",
    "Terminology management": "Управление терминологией",
    "Localization QA": "Контроль качества локализации",
    "Style guide compliance": "Соблюдение стайлгайда",
    Subtitling: "Субтитрирование",
    "Language quality review": "Оценка качества языка",
    "Legal research": "Юридическое исследование",
    "Contract drafting": "Подготовка договоров",
    "Case analysis": "Анализ дел",
    "Regulatory review": "Проверка нормативной базы",
    "Legal writing": "Юридическое письмо",
    "Corporate law basics": "Основы корпоративного права",
    "Client consultation": "Консультация клиентов",
    "Vendor sourcing": "Поиск поставщиков",
    "RFQ management": "Управление RFQ",
    "Contract negotiation": "Переговоры по контрактам",
    "Cost analysis": "Анализ затрат",
    "Purchase order management": "Управление заказами",
    "Supplier evaluation": "Оценка поставщиков",
    "Inventory coordination": "Координация запасов",
    "Spend reporting": "Отчетность по расходам",
    "Warehouse operations": "Складские операции",
    "Customs documentation": "Таможенная документация",
    "TMS systems": "TMS-системы",
    "Supplier coordination": "Координация поставщиков",
    "Delivery scheduling": "Планирование доставок",
    "Travel coordination": "Координация поездок",
    "MS Office": "MS Office",
    "Record keeping": "Ведение документации",
    Correspondence: "Деловая переписка",
    "Patient assessment": "Оценка состояния пациента",
    Diagnosis: "Диагностика",
    "Clinical documentation": "Клиническая документация",
    "Medical ethics": "Медицинская этика",
    "Electronic health records": "Электронные медкарты",
    "Emergency response": "Экстренное реагирование",
    "Preventive care": "Профилактический уход",
    "Patient education": "Обучение пациента",
    "Interdisciplinary coordination": "Междисциплинарная координация",
    "Patient care": "Уход за пациентом",
    "Vital signs monitoring": "Мониторинг жизненных показателей",
    "Medication administration": "Введение лекарств",
    "Infection control": "Инфекционный контроль",
    "Emergency support": "Экстренная помощь",
    "Care planning": "Планирование ухода",
    "Requirements gathering": "Сбор требований",
    "Stakeholder interviews": "Интервью со стейкхолдерами",
    "Gap analysis": "Gap-анализ",
    "Acceptance criteria": "Критерии приемки",
    "Backlog refinement": "Уточнение backlog",
    "SEO writing": "SEO-копирайтинг",
    Research: "Исследование",
    CMS: "CMS",
    "Tone of voice": "Тональность бренда",
    "Social media copy": "Тексты для соцсетей",
    "Email copy": "Email-тексты",
    "Vulnerability assessment": "Оценка уязвимостей",
    "Threat analysis": "Анализ угроз",
    "Security policies": "Политики безопасности",
    "Penetration testing basics": "Основы пентестов",
    "Endpoint security": "Безопасность endpoints",
    "Windows Server": "Windows Server",
    "Linux administration": "Администрирование Linux",
    "Network configuration": "Настройка сети",
    "Active Directory": "Active Directory",
    "Backup and recovery": "Резервное копирование и восстановление",
    "User access management": "Управление доступом пользователей",
    "Hardware troubleshooting": "Диагностика оборудования",
    Virtualization: "Виртуализация",
    "Monitoring tools": "Инструменты мониторинга",
    "Security patching": "Установка патчей безопасности",
  },
};

const PROFILE_LABELS: Record<ResumeLocale, Record<string, string>> = {
  uz: {
    Accountant: "Hisobchi",
    Auditor: "Auditor",
    "Financial Analyst": "Moliyaviy tahlilchi",
    "Software Developer": "Dasturchi",
    "Mobile Developer": "Mobil dasturchi",
    "DevOps Engineer": "DevOps muhandisi",
    "QA Engineer": "QA muhandisi",
    "Data Analyst": "Ma'lumotlar tahlilchisi",
    "Data Scientist": "Ma'lumotlar olimi",
    "UI UX Designer": "UI/UX dizayner",
    "Graphic Designer": "Grafik dizayner",
    "Marketing Manager": "Marketing menejeri",
    "SMM Specialist": "SMM mutaxassisi",
    "Sales Manager": "Sotuv menejeri",
    "Business Development Manager": "Biznesni rivojlantirish menejeri",
    "Recruiter HR Specialist": "HR/Recruiter mutaxassisi",
    "Project Manager": "Loyiha menejeri",
    "Product Manager": "Mahsulot menejeri",
    "Operations Manager": "Operatsion menejer",
    "Customer Support Specialist": "Mijozlarni qo'llab-quvvatlash mutaxassisi",
    Teacher: "O'qituvchi",
    Translator: "Tarjimon",
    Lawyer: "Yurist",
    "Procurement Specialist": "Xaridlar mutaxassisi",
    "Logistics Specialist": "Logistika mutaxassisi",
    "Administrative Assistant": "Ma'muriy yordamchi",
    Doctor: "Shifokor",
    Nurse: "Hamshira",
    "Business Analyst": "Biznes tahlilchi",
    "Content Writer": "Kontent yozuvchi",
    "Cybersecurity Specialist": "Kiberxavfsizlik mutaxassisi",
    "System Administrator": "Tizim administratori",
  },
  ru: {
    Accountant: "Бухгалтер",
    Auditor: "Аудитор",
    "Financial Analyst": "Финансовый аналитик",
    "Software Developer": "Разработчик ПО",
    "Mobile Developer": "Мобильный разработчик",
    "DevOps Engineer": "DevOps инженер",
    "QA Engineer": "QA инженер",
    "Data Analyst": "Аналитик данных",
    "Data Scientist": "Специалист по Data Science",
    "UI UX Designer": "UI/UX дизайнер",
    "Graphic Designer": "Графический дизайнер",
    "Marketing Manager": "Маркетинг-менеджер",
    "SMM Specialist": "SMM специалист",
    "Sales Manager": "Менеджер по продажам",
    "Business Development Manager": "Менеджер по развитию бизнеса",
    "Recruiter HR Specialist": "HR/Recruiter специалист",
    "Project Manager": "Проектный менеджер",
    "Product Manager": "Продуктовый менеджер",
    "Operations Manager": "Операционный менеджер",
    "Customer Support Specialist": "Специалист поддержки клиентов",
    Teacher: "Преподаватель",
    Translator: "Переводчик",
    Lawyer: "Юрист",
    "Procurement Specialist": "Специалист по закупкам",
    "Logistics Specialist": "Специалист по логистике",
    "Administrative Assistant": "Административный ассистент",
    Doctor: "Врач",
    Nurse: "Медсестра",
    "Business Analyst": "Бизнес-аналитик",
    "Content Writer": "Контент-райтер",
    "Cybersecurity Specialist": "Специалист по кибербезопасности",
    "System Administrator": "Системный администратор",
  },
};

export const skillProfiles: SkillProfile[] = [
  {
    label: "Software Developer",
    keywords: [
      "software developer",
      "software engineer",
      "full stack developer",
      "backend developer",
      "frontend developer",
      "frontend dasturchi",
      "backend dasturchi",
      "full stack dasturchi",
      "programmer",
      "developer",
      "dasturchi",
      "veb dasturchi",
      "razrabotchik",
      "programmist",
      "it mutaxassis",
    ],
    technical: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "REST API",
      "SQL",
      "Git",
      "Docker",
      "Unit testing",
      "Debugging",
    ],
    soft: [
      "Analytical thinking",
      "Collaboration",
      "Problem solving",
      "Ownership",
      "Communication",
    ],
  },
  {
    label: "Mobile Developer",
    keywords: [
      "mobile developer",
      "android developer",
      "ios developer",
      "react native developer",
      "flutter developer",
      "mobil ilova dasturchi",
      "mobil dasturchi",
      "android dasturchi",
      "ios dasturchi",
      "mobilnyy razrabotchik",
    ],
    technical: [
      "Kotlin",
      "Swift",
      "React Native",
      "Flutter",
      "Dart",
      "Firebase",
      "REST API",
      "Mobile UI",
      "App Store deployment",
      "Performance optimization",
    ],
    soft: ["Attention to detail", "User empathy", "Problem solving", "Communication", "Adaptability"],
  },
  {
    label: "DevOps Engineer",
    keywords: [
      "devops",
      "devops engineer",
      "site reliability engineer",
      "sre",
      "platform engineer",
      "infrastructure engineer",
      "devops mutaxassis",
      "inzhener devops",
    ],
    technical: [
      "Linux",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Terraform",
      "AWS",
      "Monitoring",
      "Shell scripting",
      "GitOps",
      "Infrastructure as code",
    ],
    soft: ["Incident management", "Collaboration", "Ownership", "Stress resilience", "Communication"],
  },
  {
    label: "QA Engineer",
    keywords: [
      "qa engineer",
      "qa tester",
      "software tester",
      "manual tester",
      "test engineer",
      "sifat nazorati",
      "tester",
      "testirovshchik",
      "kontrol kachestva",
    ],
    technical: [
      "Test case design",
      "Bug reporting",
      "Regression testing",
      "API testing",
      "Postman",
      "Selenium",
      "Jira",
      "SQL",
      "Test automation",
      "Performance testing",
    ],
    soft: ["Attention to detail", "Critical thinking", "Communication", "Persistence", "Time management"],
  },
  {
    label: "Data Analyst",
    keywords: [
      "data analyst",
      "business analyst",
      "analytics specialist",
      "data analytics",
      "analitik",
      "malumotlar tahlili",
      "ma lumotlar tahlili",
      "biznes analitik",
      "analitik dannykh",
    ],
    technical: [
      "SQL",
      "Excel",
      "Power BI",
      "Tableau",
      "Data visualization",
      "Python",
      "Statistics",
      "Dashboarding",
      "Data cleaning",
      "Reporting",
    ],
    soft: ["Analytical thinking", "Storytelling", "Attention to detail", "Communication", "Business understanding"],
  },
  {
    label: "Data Scientist",
    keywords: [
      "data scientist",
      "machine learning engineer",
      "ml engineer",
      "ai engineer",
      "suniy intellekt",
      "data science",
      "data scientist mutaxassis",
      "spetsialist po dannym",
    ],
    technical: [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Machine learning",
      "Deep learning",
      "SQL",
      "Feature engineering",
      "Model evaluation",
      "A/B testing",
    ],
    soft: ["Research mindset", "Critical thinking", "Communication", "Problem solving", "Curiosity"],
  },
  {
    label: "Accountant",
    keywords: [
      "accountant",
      "bookkeeper",
      "chief accountant",
      "buxgalter",
      "hisobchi",
      "glavnyy buxgalter",
      "finansovyy uchet",
    ],
    technical: [
      "Financial reporting",
      "General ledger",
      "Tax accounting",
      "Payroll",
      "Accounts payable",
      "Accounts receivable",
      "1C",
      "Excel",
      "Reconciliation",
      "Cost accounting",
    ],
    soft: ["Accuracy", "Integrity", "Time management", "Confidentiality", "Organization"],
  },
  {
    label: "Auditor",
    keywords: [
      "auditor",
      "internal auditor",
      "external auditor",
      "audit specialist",
      "auditor mutaxassis",
      "ichki auditor",
      "vnutrenniy auditor",
    ],
    technical: [
      "Audit planning",
      "Risk assessment",
      "Internal controls",
      "Compliance",
      "Financial statements",
      "Sampling techniques",
      "Excel",
      "Documentation",
      "Audit reporting",
      "IFRS",
    ],
    soft: ["Ethics", "Analytical thinking", "Attention to detail", "Objectivity", "Communication"],
  },
  {
    label: "Financial Analyst",
    keywords: [
      "financial analyst",
      "finance analyst",
      "investment analyst",
      "finans analitik",
      "moliyaviy analitik",
      "analitik finansov",
    ],
    technical: [
      "Financial modeling",
      "Budgeting",
      "Forecasting",
      "Variance analysis",
      "Excel advanced",
      "PowerPoint",
      "KPI tracking",
      "Valuation",
      "Scenario analysis",
      "SQL",
    ],
    soft: ["Analytical thinking", "Business acumen", "Presentation", "Accuracy", "Decision making"],
  },
  {
    label: "UI UX Designer",
    keywords: [
      "ui ux designer",
      "product designer",
      "ux designer",
      "ui designer",
      "veb dizayner",
      "dizayner interfeysa",
      "ux dizayner",
      "interfeys dizayneri",
      "web designer",
    ],
    technical: [
      "Figma",
      "Wireframing",
      "Prototyping",
      "User research",
      "Design systems",
      "Usability testing",
      "Information architecture",
      "Interaction design",
      "Accessibility",
      "Visual hierarchy",
    ],
    soft: ["Empathy", "Communication", "Creativity", "Collaboration", "Problem solving"],
  },
  {
    label: "Graphic Designer",
    keywords: [
      "graphic designer",
      "brand designer",
      "visual designer",
      "motion designer",
      "grafik dizayner",
      "graficheskiy dizayner",
      "dizayner grafiki",
    ],
    technical: [
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Adobe InDesign",
      "Brand identity",
      "Typography",
      "Layout design",
      "Social media creatives",
      "Print design",
      "Color theory",
      "Asset preparation",
    ],
    soft: ["Creativity", "Attention to detail", "Communication", "Time management", "Adaptability"],
  },
  {
    label: "Marketing Manager",
    keywords: [
      "marketing manager",
      "digital marketer",
      "marketing specialist",
      "marketolog",
      "marketing mutaxassis",
      "raqamli marketing",
      "marketolog specialist",
    ],
    technical: [
      "Market research",
      "Campaign management",
      "Content strategy",
      "Email marketing",
      "SEO",
      "Google Analytics",
      "Performance marketing",
      "Brand positioning",
      "Lead generation",
      "A/B testing",
    ],
    soft: ["Strategic thinking", "Creativity", "Communication", "Data-driven mindset", "Project coordination"],
  },
  {
    label: "SMM Specialist",
    keywords: [
      "smm specialist",
      "social media manager",
      "content manager",
      "sotsial media",
      "smm mutaxassis",
      "kontent menejer",
      "social media specialist",
    ],
    technical: [
      "Content planning",
      "Instagram marketing",
      "TikTok marketing",
      "Copywriting",
      "Canva",
      "Analytics reporting",
      "Community management",
      "Paid social ads",
      "Trend analysis",
      "Influencer collaboration",
    ],
    soft: ["Creativity", "Communication", "Adaptability", "Time management", "Audience empathy"],
  },
  {
    label: "Sales Manager",
    keywords: [
      "sales manager",
      "account executive",
      "sales specialist",
      "sales representative",
      "sotuv menejeri",
      "menedzher po prodazham",
      "prodazhi",
    ],
    technical: [
      "CRM",
      "Lead qualification",
      "Pipeline management",
      "Negotiation",
      "Sales forecasting",
      "Client presentations",
      "Objection handling",
      "Proposal writing",
      "Prospecting",
      "Upselling",
    ],
    soft: ["Persuasion", "Relationship building", "Resilience", "Communication", "Result orientation"],
  },
  {
    label: "Business Development Manager",
    keywords: [
      "business development",
      "bizdev",
      "partnership manager",
      "growth manager",
      "biznes rivojlantirish",
      "menedzher po razvitiyu biznesa",
      "bdm",
    ],
    technical: [
      "Market mapping",
      "Partnership strategy",
      "Lead generation",
      "Negotiation",
      "Deal structuring",
      "CRM",
      "Competitive analysis",
      "Proposal development",
      "Revenue planning",
      "Stakeholder management",
    ],
    soft: ["Strategic thinking", "Communication", "Networking", "Initiative", "Adaptability"],
  },
  {
    label: "Recruiter HR Specialist",
    keywords: [
      "recruiter",
      "hr specialist",
      "talent acquisition",
      "human resources",
      "kadrlar boi limi",
      "hr mutaxassis",
      "rekruter",
      "kadrovik",
    ],
    technical: [
      "Candidate sourcing",
      "Interviewing",
      "ATS",
      "Job description writing",
      "Onboarding",
      "Employer branding",
      "HR documentation",
      "Labor law basics",
      "Performance review process",
      "Compensation benchmarking",
    ],
    soft: ["Communication", "Empathy", "Confidentiality", "Negotiation", "Organization"],
  },
  {
    label: "Project Manager",
    keywords: [
      "project manager",
      "pm",
      "delivery manager",
      "project coordinator",
      "loyiha menejeri",
      "menedzher proektov",
      "project lead",
    ],
    technical: [
      "Project planning",
      "Risk management",
      "Budget control",
      "Scope management",
      "Agile",
      "Scrum",
      "Stakeholder reporting",
      "Jira",
      "Roadmap planning",
      "Resource allocation",
    ],
    soft: ["Leadership", "Communication", "Organization", "Conflict resolution", "Decision making"],
  },
  {
    label: "Product Manager",
    keywords: [
      "product manager",
      "product owner",
      "product lead",
      "prodakt menejer",
      "mahsulot menejeri",
      "menedzher produkta",
      "po",
    ],
    technical: [
      "Product strategy",
      "Roadmapping",
      "User stories",
      "Prioritization",
      "Market research",
      "A/B testing",
      "Analytics",
      "Go to market",
      "Backlog management",
      "Requirements definition",
    ],
    soft: ["Strategic thinking", "Communication", "Leadership", "Customer empathy", "Decision making"],
  },
  {
    label: "Operations Manager",
    keywords: [
      "operations manager",
      "operations specialist",
      "process manager",
      "operatsionnyy menedzher",
      "operatsiyalar menejeri",
      "biznes operatsiyalari",
    ],
    technical: [
      "Process optimization",
      "SOP development",
      "KPI management",
      "Resource planning",
      "Cross functional coordination",
      "Excel",
      "Workflow mapping",
      "Vendor management",
      "Cost optimization",
      "Reporting",
    ],
    soft: ["Organization", "Leadership", "Problem solving", "Communication", "Accountability"],
  },
  {
    label: "Customer Support Specialist",
    keywords: [
      "customer support",
      "support specialist",
      "call center",
      "customer service",
      "mijozlar bilan ishlash",
      "podderzhka klientov",
      "operator",
    ],
    technical: [
      "Ticketing systems",
      "CRM",
      "Live chat support",
      "Email support",
      "Knowledge base management",
      "Issue troubleshooting",
      "Escalation handling",
      "Service level management",
      "Call handling",
      "Product documentation",
    ],
    soft: ["Patience", "Empathy", "Communication", "Conflict resolution", "Stress resilience"],
  },
  {
    label: "Teacher",
    keywords: [
      "teacher",
      "educator",
      "tutor",
      "instructor",
      "oqituvchi",
      "muallim",
      "prepodavatel",
      "uchitel",
    ],
    technical: [
      "Lesson planning",
      "Curriculum development",
      "Classroom management",
      "Assessment design",
      "Online teaching tools",
      "Presentation skills",
      "Student progress tracking",
      "Educational technology",
      "Learning strategies",
      "Academic reporting",
    ],
    soft: ["Communication", "Patience", "Empathy", "Adaptability", "Organization"],
  },
  {
    label: "Translator",
    keywords: [
      "translator",
      "interpreter",
      "localization specialist",
      "tarjimon",
      "perevodchik",
      "lingvist",
      "language specialist",
    ],
    technical: [
      "Written translation",
      "Simultaneous interpretation",
      "CAT tools",
      "Terminology management",
      "Proofreading",
      "Localization QA",
      "Style guide compliance",
      "Subtitling",
      "Editing",
      "Language quality review",
    ],
    soft: ["Attention to detail", "Communication", "Cultural awareness", "Time management", "Confidentiality"],
  },
  {
    label: "Lawyer",
    keywords: [
      "lawyer",
      "legal counsel",
      "attorney",
      "yurist",
      "advokat",
      "yuridik maslahatchi",
      "pravoved",
    ],
    technical: [
      "Legal research",
      "Contract drafting",
      "Compliance",
      "Case analysis",
      "Regulatory review",
      "Negotiation",
      "Legal writing",
      "Corporate law basics",
      "Risk assessment",
      "Client consultation",
    ],
    soft: ["Critical thinking", "Ethics", "Communication", "Negotiation", "Attention to detail"],
  },
  {
    label: "Procurement Specialist",
    keywords: [
      "procurement specialist",
      "purchasing manager",
      "buyer",
      "supply specialist",
      "xarid mutaxassisi",
      "zakupki",
      "spetsialist po zakupkam",
    ],
    technical: [
      "Vendor sourcing",
      "RFQ management",
      "Contract negotiation",
      "Cost analysis",
      "Purchase order management",
      "Supplier evaluation",
      "Inventory coordination",
      "ERP basics",
      "Compliance documentation",
      "Spend reporting",
    ],
    soft: ["Negotiation", "Analytical thinking", "Communication", "Attention to detail", "Organization"],
  },
  {
    label: "Logistics Specialist",
    keywords: [
      "logistics specialist",
      "supply chain specialist",
      "warehouse coordinator",
      "transport manager",
      "logistika mutaxassisi",
      "logist",
      "spetsialist logistiki",
    ],
    technical: [
      "Route planning",
      "Shipment tracking",
      "Inventory management",
      "Warehouse operations",
      "Customs documentation",
      "TMS systems",
      "Cost optimization",
      "Supplier coordination",
      "Delivery scheduling",
      "Excel",
    ],
    soft: ["Organization", "Problem solving", "Communication", "Stress resilience", "Attention to detail"],
  },
  {
    label: "Administrative Assistant",
    keywords: [
      "administrative assistant",
      "office manager",
      "executive assistant",
      "administrator",
      "ofis menejeri",
      "administrator ofisa",
      "yordamchi",
    ],
    technical: [
      "Calendar management",
      "Document preparation",
      "Email management",
      "Travel coordination",
      "Meeting coordination",
      "MS Office",
      "Data entry",
      "Record keeping",
      "Office operations",
      "Correspondence",
    ],
    soft: ["Organization", "Communication", "Time management", "Discretion", "Multitasking"],
  },
  {
    label: "Doctor",
    keywords: [
      "doctor",
      "physician",
      "medical doctor",
      "vrach",
      "shifokor",
      "terapevt",
      "klinicheskiy vrach",
    ],
    technical: [
      "Patient assessment",
      "Diagnosis",
      "Treatment planning",
      "Clinical documentation",
      "Medical ethics",
      "Electronic health records",
      "Emergency response",
      "Preventive care",
      "Patient education",
      "Interdisciplinary coordination",
    ],
    soft: ["Empathy", "Communication", "Decision making", "Stress resilience", "Attention to detail"],
  },
  {
    label: "Nurse",
    keywords: [
      "nurse",
      "registered nurse",
      "clinical nurse",
      "medsestra",
      "hamshira",
      "meditsinskaya sestra",
    ],
    technical: [
      "Patient care",
      "Vital signs monitoring",
      "Medication administration",
      "Clinical documentation",
      "Infection control",
      "Emergency support",
      "Care planning",
      "Electronic health records",
      "Patient education",
      "Team coordination",
    ],
    soft: ["Empathy", "Patience", "Communication", "Attention to detail", "Stress resilience"],
  },
  {
    label: "Business Analyst",
    keywords: [
      "business analyst",
      "systems analyst",
      "process analyst",
      "biznes analitik",
      "analitik biznesa",
      "talablar analitigi",
    ],
    technical: [
      "Requirements gathering",
      "Process mapping",
      "Stakeholder interviews",
      "User stories",
      "SQL",
      "Documentation",
      "Gap analysis",
      "Acceptance criteria",
      "BPMN",
      "Backlog refinement",
    ],
    soft: ["Communication", "Analytical thinking", "Facilitation", "Problem solving", "Organization"],
  },
  {
    label: "Content Writer",
    keywords: [
      "content writer",
      "copywriter",
      "editor",
      "content creator",
      "matn yozuvchi",
      "kopirayter",
      "kontent avtor",
    ],
    technical: [
      "Copywriting",
      "SEO writing",
      "Editing",
      "Research",
      "Content planning",
      "CMS",
      "Tone of voice",
      "Proofreading",
      "Social media copy",
      "Email copy",
    ],
    soft: ["Creativity", "Communication", "Attention to detail", "Time management", "Curiosity"],
  },
  {
    label: "Cybersecurity Specialist",
    keywords: [
      "cybersecurity specialist",
      "security analyst",
      "information security",
      "soc analyst",
      "kiberxavfsizlik",
      "spetsialist po bezopasnosti",
      "infosec",
    ],
    technical: [
      "SIEM",
      "Incident response",
      "Vulnerability assessment",
      "Network security",
      "Access control",
      "Threat analysis",
      "Security policies",
      "Penetration testing basics",
      "Endpoint security",
      "Risk management",
    ],
    soft: ["Analytical thinking", "Attention to detail", "Integrity", "Communication", "Calm under pressure"],
  },
  {
    label: "System Administrator",
    keywords: [
      "system administrator",
      "sysadmin",
      "it administrator",
      "network administrator",
      "tizim administratori",
      "sistemnyy administrator",
    ],
    technical: [
      "Windows Server",
      "Linux administration",
      "Network configuration",
      "Active Directory",
      "Backup and recovery",
      "User access management",
      "Hardware troubleshooting",
      "Virtualization",
      "Monitoring tools",
      "Security patching",
    ],
    soft: ["Problem solving", "Responsibility", "Communication", "Time management", "Service mindset"],
  },
];

const PROFILE_MATCH_THRESHOLD = 1;

const CYRILLIC_TO_LATIN: Readonly<Record<string, string>> = {
  "\u0430": "a",
  "\u0431": "b",
  "\u0432": "v",
  "\u0433": "g",
  "\u0434": "d",
  "\u0435": "e",
  "\u0451": "e",
  "\u0436": "zh",
  "\u0437": "z",
  "\u0438": "i",
  "\u0439": "y",
  "\u043a": "k",
  "\u043b": "l",
  "\u043c": "m",
  "\u043d": "n",
  "\u043e": "o",
  "\u043f": "p",
  "\u0440": "r",
  "\u0441": "s",
  "\u0442": "t",
  "\u0443": "u",
  "\u0444": "f",
  "\u0445": "kh",
  "\u0446": "ts",
  "\u0447": "ch",
  "\u0448": "sh",
  "\u0449": "shch",
  "\u044a": "",
  "\u044b": "y",
  "\u044c": "",
  "\u044d": "e",
  "\u044e": "yu",
  "\u044f": "ya",
  "\u045e": "u",
  "\u049b": "q",
  "\u0493": "g",
  "\u04b3": "h",
  "\u045b": "q",
  "\u0453": "g",
  "\u04b2": "h",
};

const profileKeywordIndex: ReadonlyArray<{ profile: SkillProfile; normalizedKeywords: string[] }> =
  skillProfiles.map((profile) => ({
    profile,
    normalizedKeywords: profile.keywords.map((keyword) => normalizeText(keyword)).filter(Boolean),
  }));

export function normalizeText(value: string): string {
  const lowercase = value.toLowerCase();
  const transliterated = Array.from(lowercase)
    .map((char) => CYRILLIC_TO_LATIN[char] ?? char)
    .join("")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/['`]/g, "");

  return transliterated
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function uniqueSkills(skills: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];

  for (const skill of skills) {
    const clean = skill.trim();
    if (!clean) {
      continue;
    }

    const normalized = normalizeText(clean);
    if (!normalized || seen.has(normalized)) {
      continue;
    }

    seen.add(normalized);
    result.push(clean);
  }

  return result;
}

function scoreProfile(normalizedInput: string, normalizedKeywords: string[]): number {
  let score = 0;
  const inputTokens = normalizedInput.split(" ").filter(Boolean);

  for (const keyword of normalizedKeywords) {
    if (!keyword) {
      continue;
    }

    if (normalizedInput.includes(keyword)) {
      score += 3;
      continue;
    }

    const keywordTokens = keyword.split(" ").filter(Boolean);
    if (keywordTokens.length === 0) {
      continue;
    }

    const overlap = keywordTokens.filter((token) => token.length > 2 && inputTokens.includes(token)).length;
    if (overlap > 0) {
      score += overlap;
    }
  }

  return score;
}

function localizeSkill(skill: string, locale: ResumeLocale): string {
  const explicit = SKILL_LABELS[locale][skill];
  if (explicit) {
    return explicit;
  }
  return translateSkillFallback(skill, locale);
}

function localizeProfileLabel(label: string, locale: ResumeLocale): string {
  return PROFILE_LABELS[locale][label] || label;
}

const SKILL_PHRASE_FALLBACK: Record<ResumeLocale, Record<string, string>> = {
  uz: {
    "app store deployment": "App Store'ga joylash",
    "unit testing": "Unit test yozish",
    "bug reporting": "Xatolarni hisobotlash",
    "test case design": "Test holatlarini loyihalash",
    "regression testing": "Regression test",
    "api testing": "API testlash",
    "performance testing": "Ishlash testlari",
    "data visualization": "Ma'lumotlarni vizualizatsiya qilish",
    "data cleaning": "Ma'lumotlarni tozalash",
    "market research": "Bozor tadqiqoti",
    "email marketing": "Email marketing",
    "content strategy": "Kontent strategiyasi",
    "lead generation": "Lid yaratish",
    "campaign management": "Kampaniyalarni boshqarish",
    "candidate sourcing": "Nomzod izlash",
    "job description writing": "Vakansiya matnini yozish",
    "labor law basics": "Mehnat qonunchiligi asoslari",
    "project planning": "Loyiha rejalashtirish",
    "risk management": "Risklarni boshqarish",
    "budget control": "Byudjet nazorati",
    "scope management": "Scope boshqaruvi",
    "resource allocation": "Resurs taqsimoti",
    "product strategy": "Mahsulot strategiyasi",
    prioritization: "Ustuvorlashtirish",
    roadmapping: "Yo'l xaritasi tuzish",
    "process optimization": "Jarayonlarni optimallashtirish",
    "vendor management": "Ta'minotchilarni boshqarish",
    "cost optimization": "Xarajatlarni optimallashtirish",
    "service level management": "Xizmat darajasini boshqarish",
    "issue troubleshooting": "Muammolarni bartaraf etish",
    "calendar management": "Kalendarni boshqarish",
    "document preparation": "Hujjat tayyorlash",
    "meeting coordination": "Uchrashuvlarni muvofiqlashtirish",
    "route planning": "Yo'nalishni rejalashtirish",
    "shipment tracking": "Yukni kuzatish",
    "inventory management": "Zaxira boshqaruvi",
    "patient care": "Bemor parvarishi",
    diagnosis: "Tashxis qo'yish",
    "treatment planning": "Davolash rejasini tuzish",
    "requirements gathering": "Talablarni yig'ish",
    "process mapping": "Jarayon xaritalash",
    facilitation: "Fasilitatsiya",
    copywriting: "Kopirayting",
    editing: "Tahrirlash",
    proofreading: "Korrektura",
    "incident response": "Insidentga javob",
    "network security": "Tarmoq xavfsizligi",
    "access control": "Kirish nazorati",
  },
  ru: {
    "app store deployment": "Публикация в App Store",
    "unit testing": "Юнит-тестирование",
    "bug reporting": "Репортинг багов",
    "test case design": "Проектирование тест-кейсов",
    "regression testing": "Регрессионное тестирование",
    "api testing": "Тестирование API",
    "performance testing": "Тестирование производительности",
    "data visualization": "Визуализация данных",
    "data cleaning": "Очистка данных",
    "market research": "Исследование рынка",
    "email marketing": "Email-маркетинг",
    "content strategy": "Контент-стратегия",
    "lead generation": "Лидогенерация",
    "campaign management": "Управление кампаниями",
    "candidate sourcing": "Поиск кандидатов",
    "job description writing": "Написание описаний вакансий",
    "labor law basics": "Основы трудового права",
    "project planning": "Планирование проекта",
    "risk management": "Управление рисками",
    "budget control": "Контроль бюджета",
    "scope management": "Управление scope",
    "resource allocation": "Распределение ресурсов",
    "product strategy": "Продуктовая стратегия",
    prioritization: "Приоритизация",
    roadmapping: "Построение roadmap",
    "process optimization": "Оптимизация процессов",
    "vendor management": "Управление поставщиками",
    "cost optimization": "Оптимизация затрат",
    "service level management": "Управление уровнем сервиса",
    "issue troubleshooting": "Устранение проблем",
    "calendar management": "Управление календарем",
    "document preparation": "Подготовка документов",
    "meeting coordination": "Координация встреч",
    "route planning": "Планирование маршрутов",
    "shipment tracking": "Отслеживание поставок",
    "inventory management": "Управление запасами",
    "patient care": "Уход за пациентами",
    diagnosis: "Диагностика",
    "treatment planning": "Планирование лечения",
    "requirements gathering": "Сбор требований",
    "process mapping": "Картирование процессов",
    facilitation: "Фасилитация",
    copywriting: "Копирайтинг",
    editing: "Редактирование",
    proofreading: "Вычитка",
    "incident response": "Реагирование на инциденты",
    "network security": "Сетевая безопасность",
    "access control": "Контроль доступа",
  },
};

const SKILL_WORD_FALLBACK: Record<ResumeLocale, Record<string, string>> = {
  uz: {
    financial: "moliyaviy",
    reporting: "hisobot",
    general: "umumiy",
    ledger: "kitob",
    tax: "soliq",
    accounting: "hisobi",
    accounts: "hisoblar",
    payable: "to'lov",
    receivable: "qabul",
    analysis: "tahlil",
    management: "boshqaruvi",
    planning: "rejalashtirish",
    strategy: "strategiya",
    control: "nazorat",
    optimization: "optimallashtirish",
    operations: "operatsiyalar",
    operation: "operatsiya",
    project: "loyiha",
    product: "mahsulot",
    business: "biznes",
    customer: "mijoz",
    support: "qo'llab-quvvatlash",
    specialist: "mutaxassis",
    engineer: "muhandis",
    administrator: "administrator",
    developer: "dasturchi",
    analyst: "tahlilchi",
    designer: "dizayner",
    manager: "menejer",
    recruiter: "rekruter",
    security: "xavfsizlik",
    network: "tarmoq",
    data: "ma'lumot",
    quality: "sifat",
    service: "xizmat",
    level: "daraja",
    response: "javob",
    monitoring: "monitoring",
    performance: "samaradorlik",
    testing: "testlash",
    design: "dizayn",
    documentation: "hujjatlash",
    communication: "muloqot",
    coordination: "muvofiqlashtirish",
    research: "tadqiqot",
    compliance: "muvofiqlik",
    risk: "risk",
    assessment: "baholash",
    cloud: "bulut",
  },
  ru: {
    financial: "финансовый",
    reporting: "отчетность",
    general: "главный",
    ledger: "реестр",
    tax: "налоговый",
    accounting: "учет",
    accounts: "счета",
    payable: "кредиторский",
    receivable: "дебиторский",
    analysis: "анализ",
    management: "управление",
    planning: "планирование",
    strategy: "стратегия",
    control: "контроль",
    optimization: "оптимизация",
    operations: "операции",
    operation: "операция",
    project: "проект",
    product: "продукт",
    business: "бизнес",
    customer: "клиент",
    support: "поддержка",
    specialist: "специалист",
    engineer: "инженер",
    administrator: "администратор",
    developer: "разработчик",
    analyst: "аналитик",
    designer: "дизайнер",
    manager: "менеджер",
    recruiter: "рекрутер",
    security: "безопасность",
    network: "сеть",
    data: "данные",
    quality: "качество",
    service: "сервис",
    level: "уровень",
    response: "реагирование",
    monitoring: "мониторинг",
    performance: "производительность",
    testing: "тестирование",
    design: "дизайн",
    documentation: "документация",
    communication: "коммуникация",
    coordination: "координация",
    research: "исследование",
    compliance: "комплаенс",
    risk: "риск",
    assessment: "оценка",
    cloud: "облако",
  },
};

function translateSkillFallback(skill: string, locale: ResumeLocale): string {
  // Keep already-localized or mixed-script values untouched.
  if (/[А-Яа-яЁёЎўҚқҒғҲҳ]/.test(skill)) {
    return skill;
  }

  const phraseDict = SKILL_PHRASE_FALLBACK[locale];
  const wordDict = SKILL_WORD_FALLBACK[locale];
  const normalized = skill.toLowerCase().trim();

  if (phraseDict[normalized]) {
    return phraseDict[normalized];
  }

  // Preserve well-known technical abbreviations and stack names.
  if (/^(AI|ML|SQL|AWS|GCP|Azure|API|REST|GraphQL|CI\/CD|SRE|KPI|OKR|ERP|CRM|SIEM|IFRS|BPMN|ATS|A\/B)$/i.test(skill)) {
    return skill;
  }

  const translated = skill.replace(/[A-Za-z]+/g, (word) => {
    const lower = word.toLowerCase();
    return wordDict[lower] || word;
  });

  return translated;
}

export function detectSkillProfile(input: string): SkillProfile | null {
  const normalizedInput = normalizeText(input);
  if (!normalizedInput) {
    return null;
  }

  let bestProfile: SkillProfile | null = null;
  let bestScore = 0;

  for (const entry of profileKeywordIndex) {
    const score = scoreProfile(normalizedInput, entry.normalizedKeywords);
    if (score > bestScore) {
      bestScore = score;
      bestProfile = entry.profile;
    }
  }

  if (bestScore < PROFILE_MATCH_THRESHOLD) {
    return null;
  }

  return bestProfile;
}

export function getSkillSuggestions(
  input: string,
  selectedTechnical: string[],
  selectedSoft: string[],
  locale: ResumeLocale = "uz"
): {
  profile: SkillProfile | null;
  technical: string[];
  soft: string[];
} {
  const profile = detectSkillProfile(input);
  const selectedTechnicalSet = new Set(
    selectedTechnical.map((skill) => normalizeText(skill)).filter(Boolean)
  );
  const selectedSoftSet = new Set(
    selectedSoft.map((skill) => normalizeText(skill)).filter(Boolean)
  );

  const technicalPool = [...(profile?.technical ?? []), ...commonSkills.technical].map((skill) =>
    localizeSkill(skill, locale)
  );
  const softPool = [...(profile?.soft ?? []), ...commonSkills.soft].map((skill) =>
    localizeSkill(skill, locale)
  );

  const technicalSuggestions = uniqueSkills(technicalPool).filter(
    (skill) => !selectedTechnicalSet.has(normalizeText(skill))
  );
  const softSuggestions = uniqueSkills(softPool).filter(
    (skill) => !selectedSoftSet.has(normalizeText(skill))
  );

  return {
    profile: profile ? { ...profile, label: localizeProfileLabel(profile.label, locale) } : null,
    technical: technicalSuggestions.slice(0, 12),
    soft: softSuggestions,
  };
}
